# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qtui import ui_listausuarios, ui_login, ui_main, ui_registro 
import utils
from utils import qtPopup



class UiObject(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(319, 215)
        Login.setAutoFillBackground(False)
        Login.setStyleSheet("background-color: rgb(29, 29, 29);")
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 61, 21))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.entry_usuario = QtWidgets.QLineEdit(self.centralwidget)
        self.entry_usuario.setGeometry(QtCore.QRect(10, 80, 301, 20))
        self.entry_usuario.setStyleSheet("QLineEdit {background-color: rgb(186, 186, 186);border-radius:5px} QLineEdit:focus {border: 1.5px solid #796868}")
        self.entry_usuario.setObjectName("entry_usuario")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 61, 21))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.entry_senha = QtWidgets.QLineEdit(self.centralwidget)
        self.entry_senha.setGeometry(QtCore.QRect(10, 130, 301, 20))
        self.entry_senha.setStyleSheet("QLineEdit {background-color: rgb(186, 186, 186);border-radius:5px} QLineEdit:focus {border: 1.5px solid #796868}")
        self.entry_senha.setInputMask("")
        self.entry_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.entry_senha.setObjectName("entry_senha")
        self.mainlabel = QtWidgets.QLabel(self.centralwidget)
        self.mainlabel.setGeometry(QtCore.QRect(10, 0, 301, 41))
        self.mainlabel.setStyleSheet("")
        self.mainlabel.setObjectName("mainlabel")
        self.bt_logar = QtWidgets.QPushButton(self.centralwidget)
        self.bt_logar.setGeometry(QtCore.QRect(200, 180, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.bt_logar.setFont(font)
        self.bt_logar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_logar.setStyleSheet("""
QPushButton {
background-color: rgb(210, 210, 210);
border-radius: 15px;
}
:hover {
background-color: rgb(230, 230, 230);
}
""")
        self.bt_logar.setCheckable(False)
        self.bt_logar.setObjectName("bt_logar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 150, 131, 21))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.bt_registro = QtWidgets.QLabel(self.centralwidget)
        self.bt_registro.setGeometry(QtCore.QRect(110, 150, 91, 21))
        self.bt_registro.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_registro.setStyleSheet("QLabel {color: rgb(91, 191, 202);}"
                                       "QLabel::hover {color: rgb(58, 173, 185)}")
        self.bt_registro.setObjectName("bt_registro")
        self.bt_registro.mousePressEvent = self.openRegisterWindow

        self.bt_logar.clicked.connect(self.tryLogin)
        
        self.centralwidget.keyPressEvent = self.keyPressEvent

        self.thisWindow = Login
        Login.setCentralWidget(self.centralwidget)


        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def openRegisterWindow(self, event):
        self.thisWindow.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = ui_registro.UiObject()
        self.ui.setupUi(self.window)
        self.window.show()

    def tryLogin(self):
        if self.entry_usuario.text() == "" or self.entry_senha.text() == "": # Não preencheu os campos
            qtPopup("Erro ao tentar logar", "Preencha todos os campos para realizar login", "Warning")
            return
    
        senhadousuario = utils.dbQuery(f"SELECT senha FROM users WHERE usuario='{self.entry_usuario.text()}'")

        if senhadousuario is None: # Usuário não existe
            qtPopup("Erro ao tentar logar", "Usuário e/ou senha incorreto(s)", "Warning")
            return
        
        if self.entry_senha.text() != senhadousuario[0][0]: # Senha incorreta para o usuário
            qtPopup("Erro ao tentar logar", "Usuário e/ou senha incorreto(s)", "Warning")
            return
        
        with open('session.txt', 'w') as f:
            f.write(self.entry_usuario.text())

        self.thisWindow.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = ui_main.UiObject()
        self.ui.setupUi(self.window)
        self.window.show()

    def keyPressEvent(self, event):
        if (event.key() == 16777220) or (event.key() == 16777221): 
            self.tryLogin()

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login - CRUD"))
        self.label_3.setText(_translate("Login", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Usuário</span></p></body></html>"))
        self.label_2.setText(_translate("Login", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Senha</span></p></body></html>"))
        self.mainlabel.setText(_translate("Login", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#ff0000;\">Login</span></p></body></html>"))
        self.bt_logar.setWhatsThis(_translate("Login", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.bt_logar.setText(_translate("Login", "Realizar login"))
        self.label.setText(_translate("Login", "<html><head/><body><p>Não tem uma conta? </p></body></html>"))
        self.bt_registro.setText(_translate("Login", "<html><head/><body><p><span style=\" text-decoration: underline;\">Registre-se agora</span></p></body></html>"))


def showWindow():
    window = QtWidgets.QMainWindow()
    ui = UiObject()
    ui.setupUi(window)
    window.show()
