# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'not-converted-ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qtui import ui_listausuarios, ui_login, ui_main, ui_registro


class UiObject(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(480, 266)
        Main.setStyleSheet("background-color: rgb(29, 29, 29);")
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -20, 471, 251))
        self.label.setObjectName("label")
        Main.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(Main)
        self.toolBar.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(90, 90, 90);")
        self.toolBar.setObjectName("toolBar")
        Main.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_cadastrousuarios = QtWidgets.QAction(Main)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("qtui/images/usuarios.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_cadastrousuarios.setIcon(icon)
        self.action_cadastrousuarios.setObjectName("action_cadastrousuarios")
        self.action_sair = QtWidgets.QAction(Main)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("qtui/images/sair.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_sair.setIcon(icon1)
        self.action_sair.setObjectName("action_sair")
        self.toolBar.addAction(self.action_sair)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_cadastrousuarios)
        self.action_cadastrousuarios.triggered.connect(self.abrirCadastro)
        self.action_sair.triggered.connect(self.returnToLogin)
        self.thisWindow = Main

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def abrirCadastro(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = ui_listausuarios.UiObject()
        self.ui.setupUi(self.window)
        self.window.show()

    def returnToLogin(self):
        with open('session.txt', 'w') as f:
            f.write("")
        self.thisWindow.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = ui_login.UiObject()
        self.ui.setupUi(self.window)
        self.window.show()

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Página Inicial - CRUD"))
        self.label.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; color:#ffffff;\">C R U D</span></p></body></html>"))
        self.toolBar.setWindowTitle(_translate("Main", "toolBar"))
        self.action_cadastrousuarios.setText(_translate("Main", "Cadastro de Usuários"))
        self.action_sair.setText(_translate("Main", "Sair"))
        self.action_sair.setToolTip(_translate("Main", "Sair"))


def showWindow():
    window = QtWidgets.QMainWindow()
    ui = UiObject()
    ui.setupUi(window)
    window.show()