# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registro.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qtui import ui_listausuarios, ui_login, ui_main, ui_registro 
import utils
from utils import qtPopup

import re
regex = '^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$'
      
def EmailCheck(email):  
    if(re.search(regex,email)):  
        return True
    else:  
        return False

class UiObject(object):
    def setupUi(self, Registro):
        Registro.setObjectName("Registro")
        Registro.resize(573, 303)
        Registro.setStyleSheet("""background-color: rgb(29, 29, 29);""")
        self.centralwidget = QtWidgets.QWidget(Registro)
        self.centralwidget.setObjectName("centralwidget")
        self.mainlabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.mainlabel_2.setGeometry(QtCore.QRect(10, 0, 561, 41))
        self.mainlabel_2.setStyleSheet("")
        self.mainlabel_2.setObjectName("mainlabel_2")
        self.entry_usuario = QtWidgets.QLineEdit(self.centralwidget)
        self.entry_usuario.setGeometry(QtCore.QRect(10, 80, 241, 20))
        self.entry_usuario.setStyleSheet("QLineEdit {background-color: rgb(186, 186, 186);border-radius:5px} QLineEdit:focus {border: 1.5px solid #796868}")
        self.entry_usuario.setObjectName("entry_usuario")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 60, 61, 21))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 61, 21))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.entry_senha = QtWidgets.QLineEdit(self.centralwidget)
        self.entry_senha.setGeometry(QtCore.QRect(10, 120, 241, 20))
        self.entry_senha.setStyleSheet("QLineEdit {background-color: rgb(186, 186, 186);border-radius:5px} QLineEdit:focus {border: 1.5px solid #796868}")
        self.entry_senha.setObjectName("entry_senha")
        self.entry_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.entry_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.entry_nome.setGeometry(QtCore.QRect(10, 170, 241, 20))
        self.entry_nome.setStyleSheet("QLineEdit {background-color: rgb(186, 186, 186);border-radius:5px} QLineEdit:focus {border: 1.5px solid #796868}")
        self.entry_nome.setObjectName("entry_nome")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 241, 21))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 241, 21))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 250, 241, 21))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.entry_cpf = QtWidgets.QLineEdit(self.centralwidget)
        self.entry_cpf.setGeometry(QtCore.QRect(10, 270, 241, 20))
        self.entry_cpf.setStyleSheet("QLineEdit {background-color: rgb(186, 186, 186);border-radius:5px} QLineEdit:focus {border: 1.5px solid #796868}")
        self.entry_cpf.setObjectName("entry_cpf")
        self.entry_cpf.setInputMask("999.999.999-99")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(290, 60, 241, 21))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.entry_email = QtWidgets.QLineEdit(self.centralwidget)
        self.entry_email.setGeometry(QtCore.QRect(290, 80, 271, 20))
        self.entry_email.setStyleSheet("QLineEdit {background-color: rgb(186, 186, 186);border-radius:5px} QLineEdit:focus {border: 1.5px solid #796868}")
        self.entry_email.setObjectName("entry_email")
        self.entry_celular = QtWidgets.QLineEdit(self.centralwidget)
        self.entry_celular.setGeometry(QtCore.QRect(290, 120, 271, 20))
        self.entry_celular.setStyleSheet("QLineEdit {background-color: rgb(186, 186, 186);border-radius:5px} QLineEdit:focus {border: 1.5px solid #796868}")
        self.entry_celular.setObjectName("entry_celular")
        self.entry_celular.setInputMask("(99) 99999-9999")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(290, 100, 241, 21))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.entry_nasc = QtWidgets.QDateEdit(self.centralwidget)
        self.entry_nasc.setGeometry(QtCore.QRect(10, 220, 241, 22))
        self.entry_nasc.setStyleSheet("QDateEdit {background-color: rgb(186, 186, 186);border-radius:5px} QDateEdit:focus {border: 1.5px solid #796868}")
        self.entry_nasc.setObjectName("entry_nasc")
        self.divisoria = QtWidgets.QFrame(self.centralwidget)
        self.divisoria.setGeometry(QtCore.QRect(260, 50, 16, 281))
        self.divisoria.setStyleSheet("")
        self.divisoria.setFrameShape(QtWidgets.QFrame.VLine)
        self.divisoria.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.divisoria.setObjectName("divisoria")
        self.box_tos = QtWidgets.QCheckBox(self.centralwidget)
        self.box_tos.setGeometry(QtCore.QRect(290, 150, 281, 17))
        self.box_tos.setStyleSheet("color: rgb(255, 255, 255);")
        self.box_tos.setObjectName("box_tos")
        self.bt_registrar = QtWidgets.QPushButton(self.centralwidget)
        self.bt_registrar.setGeometry(QtCore.QRect(370, 260, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.bt_registrar.setFont(font)
        self.bt_registrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_registrar.setStyleSheet("QPushButton {background-color: rgb(210, 210, 210);border-radius: 15px;}QPushButton:hover {background-color: rgb(230, 230, 230);}")
        self.bt_registrar.setCheckable(False)
        self.bt_registrar.setObjectName("bt_registrar")
        self.label_7.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.mainlabel_2.raise_()
        self.entry_usuario.raise_()
        self.entry_senha.raise_()
        self.entry_nome.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.entry_cpf.raise_()
        self.label_6.raise_()
        self.entry_email.raise_()
        self.entry_celular.raise_()
        self.entry_nasc.raise_()
        self.divisoria.raise_()
        self.box_tos.raise_()
        self.bt_registrar.raise_()

        self.thisWindow = Registro
        Registro.setCentralWidget(self.centralwidget)

        self.bt_registrar.clicked.connect(self.registrar)

        self.retranslateUi(Registro)
        QtCore.QMetaObject.connectSlotsByName(Registro)

    def registrar(self):
        #self.box_tos.checkState()  - 2
        if self.entry_usuario.text() == "" or self.entry_senha.text() == "" or self.entry_nome.text() == "" or self.entry_nasc.text() == "" or self.entry_cpf.text().strip() == "..-" or self.entry_email.text() == "" or self.entry_celular.text().strip() == "() -": # Se houver algum campo vazio
            qtPopup("Erro ao registrar", "Preencha todos os campos para se registrar!", "Warning")
            return
        if len(self.entry_nome.text().split()) < 2: # Validação de nome completo
            qtPopup("Erro ao registrar", "Coloque um nome válido!", "Warning")
            return
        if len(self.entry_senha.text().strip()) < 4: # Validação de senha
            qtPopup("Erro ao registrar", "Sua senha precisa ter pelo menos 4 caracteres!", "Warning")
            return
        if len(self.entry_cpf.text().strip()) != 14: # Validação de CPF
            qtPopup("Erro ao registrar", "Coloque um CPF válido!", "Warning")
            return
        if not EmailCheck(self.entry_email.text()): # Validação de Email
            qtPopup("Erro ao registrar", "Coloque um e-mail válido!", "Warning")
            return
        if len(self.entry_celular.text().strip()) != 15: # Validação de Número
            qtPopup("Erro ao registrar", "Coloque um número de celular válido!", "Warning")
            return
        if self.box_tos.checkState() != 2: # Validação de ToS
            qtPopup("Erro ao registrar", "Você precisa aceitar os Termos de Uso e Política de Privacidade para se registrar!", "Warning")
            return

        t_cpf = self.entry_cpf.text().replace(".", "").replace("-", "")
        t_celular = int(self.entry_celular.text().replace("(", "").replace(")", "").replace("-", "").replace(" ", ""))
        
        if utils.dbQuery(f"SELECT * FROM users WHERE usuario='{self.entry_usuario.text().strip()}'") is not None: # Validação de usuário - se já existe
            qtPopup("Erro ao registrar", "Esse nome de usuário já está em uso, tente novamente!", "Warning")
            return
        if utils.dbQuery(f"SELECT * FROM users WHERE cpf='{t_cpf}'") is not None: # Validação de CPF - se já existe
            qtPopup("Erro ao registrar", "Esse CPF já está registrado, tente novamente!", "Warning")
            return
        if utils.dbQuery(f"SELECT * FROM users WHERE email='{self.entry_email.text().strip()}'") is not None: # Validação de E-mail - se já existe
            qtPopup("Erro ao registrar", "Esse e-mail já está registrado, tente novamente!", "Warning")
            return
        if utils.dbQuery(f"SELECT * FROM users WHERE numerocelular='{t_celular}'") is not None: # Validação de Número - se já existe
            qtPopup("Erro ao registrar", "Esse número de celular já está registrado, tente novamente!", "Warning")
            return


        utils.dbQuery(f"INSERT INTO users(usuario, senha, nome, datanascimento, cpf, email, numerocelular) VALUES('{self.entry_usuario.text().strip()}', '{self.entry_senha.text().strip()}', '{self.entry_nome.text().strip()}', '{self.entry_nasc.text()}', '{t_cpf}', '{self.entry_email.text()}', '{t_celular}')")
        qtPopup("Registrado(a)", "Você foi registrado(a) com sucesso! Faça login com seu usuário e senha", "Information")
        self.returnToLogin()

    def returnToLogin(self):
        self.thisWindow.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = ui_login.UiObject()
        self.ui.setupUi(self.window)
        self.window.show()

    def retranslateUi(self, Registro):
        _translate = QtCore.QCoreApplication.translate
        Registro.setWindowTitle(_translate("Registro", "Registro - CRUD"))
        self.mainlabel_2.setText(_translate("Registro", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#ff0000;\">Registro</span></p></body></html>"))
        self.label.setText(_translate("Registro", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Usuário</span></p></body></html>"))
        self.label_2.setText(_translate("Registro", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Senha</span></p></body></html>"))
        self.label_3.setText(_translate("Registro", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Nome completo</span></p></body></html>"))
        self.label_4.setText(_translate("Registro", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Data de Nascimento</span></p></body></html>"))
        self.label_5.setText(_translate("Registro", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">CPF</span></p></body></html>"))
        self.label_6.setText(_translate("Registro", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">E-mail</span></p></body></html>"))
        self.label_7.setText(_translate("Registro", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Número de Celular</span></p></body></html>"))
        self.box_tos.setText(_translate("Registro", "Li e aceito os Termos de Uso e Política de Privacidade"))
        self.bt_registrar.setWhatsThis(_translate("Registro", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.bt_registrar.setText(_translate("Registro", "Registrar"))


def showWindow():
    window = QtWidgets.QMainWindow()
    ui = UiObject()
    ui.setupUi(window)
    window.show()